config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post  "follow/account" => "accounts#follow_account", as: :follow_account

  resources :posts, only:[:new, :create, :show]
  resources :comments, only:[:create]
  root to: "public#homepage"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  has_many :posts
  has_many :likes

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following
    Follower.where(following_id: self.id).count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account
  validates_presence_of :comment
  validates_presence_of :account_id
  validates_presence_of :post_id

  attr_accessor :return_to 

  after_create :increase_post_comment_counter
  after_destroy :decrease_post_comment_counter

  private
  def increase_post_comment_counter
    Post.find(self.post_id).increment(:total_comments_count).save
  end

  def decrease_post_comment_counter
    Post.find(self.post_id).decrement(:total_comments_count).save 
  end
end

app/models/follower.rb
class Follower < ApplicationRecord
  # belongs_to :accounts
  validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :post
  belongs_to :account

  validates_uniqueness_of :post_id, scope: :account_id

  after_create :increase_post_like_counter
  after_destroy :decrease_post_like_counter

  private
  def increase_post_like_counter
    Post.find(self.post_id).increment(:total_likes_count).save
  end

  def decrease_post_like_counter
    Post.find(self.post_id).decrement(:total_likes_count).save
  end
end

app/models/likes.rb
class Like < ApplicationRecord

  belongs_to :post
  belongs_to :account
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order created_at: :desc}
  mount_uploader :image, ImageUploader
  belongs_to :account
  before_create :set_active
  scope :active, -> {where active: true}
  has_many :likes
  has_many :comments
  
  private
  def set_active
    self.active = true
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_account, only: [:profile ]
  def index

    followers_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    followers_ids << current_account.id 
    @posts = Post.includes(:account).where(account_id: followers_ids)
    @comment = Comment.new

    following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    following_ids << current_account.id
    @follower_suggestions = Account.where.not(id: following_ids)
    
  end

  def profile
    @posts = @account.posts.active
  end

  def follow_account
    follower_id = params[:follow_id]
    if Follower.create!(follower_id: current_account.id, following_id: follower_id)
     flash[:success] = "Now following user"
    else
      flash[:danger] = "Unable to add following"
    end
    redirect_to dashboard_path
  end

  private

  def set_account
    @account = Account.find_by_username(params[:username])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :image, :image_cache, :description, :website])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_account!

  def create
    @comment = Comment.new(comment_params)
    @comment.account_id = current_account.id if account_signed_in?

    if @comment.save
      return_url = params[:comment][:return_to].present? ?  post_path(@comment.post_id) : dashboard_path
      redirect_to return_url, flash:{ success: "Comment was created successfully"}
    else
      redirect_to dashboard_path, flash:{ danger: "Comment was not saved"}
    end
  end
  
  private
  
  def comment_params
  params.require(:comment).permit(:comment, :post_id, :return_to)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_account!

  def save_like
    @like = Like.new(post_id: params[:post_id], account_id: current_account.id)
    @post_id = params[:post_id]
    existing_like = Like.where(post_id: params[:post_id], account_id: current_account.id)
      respond_to do |format|
         format.js{
           if existing_like.any?
            existing_like.first.destroy
            @success = false
           elsif @like.save
          @success = true
         else
          @success = false
         end
         @post_likes = Post.find(@post_id).total_likes_count
         render "posts/like"
        }      
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_post
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?

    if @post.save
      redirect_to dashboard_path, flash:{ success: "Post was created successfully"}
    else
      redirect_to new_post_path, flash:{ danger: "Post was not saved"}
    end
  end
  
  def show
    @comment = Comment.new
    @comments = Comment.includes(:account).where(post_id: @post.id)
  end

  private

  def set_post
    @post = Post.find(params[:id]) if params[:id].present?
  end
  
  def post_params
  params.require(:post).permit(:description, :image,:image_cache)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def homepage
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper

  def profile_picture account, width = 100
    image_path = account.image.present? ? account.image.url : "default.png"
    image_tag(image_path,width: width, class: "img-circle m-r-10")
  end

  def can_edit_profile? profile_id
    account_signed_in? && current_account.id == profile_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_liked_user? post_id
    Like.where(post_id: post_id,account_id: current_account.id).any?
    
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account|%>
  <div class="recommended-follower">
    <div class="row">
      <div class="col-sm--3 col-lg-2">
      <%= link_to profile_picture(account, 40), profile_path(account.username) %>
    </div>
    <div class="col-sm-9 col-lg-10">
      <%= form_tag follow_account_path, method: :post, class:"float-right" do %>
        <%=  hidden_field_tag  :follow_id, account.id %>
        <%= submit_tag "Follow", class:"btn btn-info btn-sm" %>
      <% end %>
     <%= link_to account.username, profile_path(account.username), class:"text-dark"%>
     <p class="text-muted"><%= account.created_at > 2.days.ago ? "New to Instagram" : "Followed by X user" %></p>
     </div>
  </div>
</div>
<% end %>

app/views/accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <% @posts.each do |post|%>
        <div class="insta-post">
          <div class="post-meta">
            <%= link_to image_tag(post.account.image.thumb.url, class:"img-circle"), profile_path(post.account.username) %>
            <%= link_to post.account.username, profile_path(post.account.username), class:"text-dark"%>
          </div>        
        <%= image_tag post.image.url, class:"img img-fluid"%> 

       
  
        <div class="post-details">
           <div class="post-actions">
          <i class="fa fa-heart like-<%= post.id %><%= "active" if post_liked_user?(post.id)%> fa-2x post-like" data-id="<%= post.id%>"></i>
          <%= link_to post_path(post.id) do %>
          <i class="fa fa-comment fa-2x post-commnet"></i>
          <% end %>
        </div>
          <p><strong id="post-<%= post.id%>-likes"><%= post.total_likes_count %>Likes</strong></p>
          <p><strong id="post-<%= post.id%>-comment"><%= link_to post.account.username,profile_path(post.account.username), class:"text-dark" %></strong></p>
          <%= simple_format post.description %>
          <p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p>

          <%= render "posts/comments", post: post, comments: Comment.includes(:account).where(post_id: post.id) %>
        </div>
        <div class="comment-box">
          <%= form_for @comment do |f| %>
          <%= f.hidden_field :post_id, value: post.id%>
          <div class="input-group">
          <%= f.text_field :comment, placeholder:"Add comment here...", class:"form-control post-comment" %>
          <div class="input-group-append">
          <%= f.submit "Post", class:"btn btn-success float-right"%>
          </div>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
      <div class="col-4">
        <div class="account-summary">
          <p class="m-0">
          <%= link_to image_tag(current_account.image.thumb.url, class:"img-circle float-left m-r-15"), profile_path(current_account.username) if current_account.image.present? %>
          <strong><%= current_account.username %></strong><br />
          <%= current_account.full_name %>
          </p>
        </div>
        <div class="follower-suggestions">
          <%= link_to "View All", "#",class:"float-right text-dark" %>
          <p class="text-muted">Suggestions for you</p>
          <%= render "accounts/follower_suggestions"%>
        </div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= profile_picture @account, 200 %>
    </div>
    <div class="col-8 text-left">
    <div class="col-6">
      <div class="row">
        <h3><%= @account.full_name %><h3>
        <%= link_to "Edit Profile", edit_account_registration_path, class:"btn btn-muted btn-custom float-right" if can_edit_profile?(@account.id)%>
      </div>
    </div>

    <div class="row profile-stats">
      <div class="col-4">
        <%= @account.posts.count %>posts
      </div>
      <div class="col-4">
        <%= @account.total_followers %>followers
      </div>
      <div class="col-4">
        <%= @account.total_following %>following
      </div>
    </div>
    
    <p><%= @account.full_name %></p>
    <%= simple_format @account.description %>
    <p><%= link_to @account.website if @account.website.present? %></p>
    </div>
  </div>
     <div class="row profile-posts">
      <% @posts.each do |post| %>       
        <div class="col-4">
          <div class="insta-post post-square" style="background: url(<%= post.image.url %>) no-repeat center top">
           <%= link_to post_path(post) do %>
            <div class="post-stats">
            <div class="inner">
              <i class="fa fa-heart"></i><%= post.total_likes_count %> 
              <i class="fa fa-comment m-l-15"></i><%= post.total_comments_count %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/_account_nav.html.erb
<li class="nav-item active">
  <%= link_to "Dashboard", dashboard_path, class:"nav-link"%>
</li>
<li class="nav-item">
  <%= link_to "New Post", new_post_path, class:"nav-link"%>
</li>
<li class="nav-item">
  <%= link_to "My Profile",profile_path(current_account.username), class:"nav-link"%>
</li>
<li class="nav-item">
  <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class:"nav-link"%>
</li>

app/views/layouts/_public_nav.html.erb
<li class="nav-item active">
  <a class="nav-link" href="/">Home
  <span class="sr-only">(current)</span>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">About</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Services</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Contact</a>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>InstagramClone</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white static-top">
    <div class="container">
      <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path%>">
      
        <p style="font-family: cursive;">Instagram</p>
      
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
         <% if account_signed_in? %>
          <%= render "layouts/account_nav"%>
        <% else %>
          <%= render "layouts/public_nav" %>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
       <%= yield %> 
      </div>
    </div>
  </div>
   
  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment|%>
<div class="comment">
  <%= link_to profile_picture(comment.account, 25), profile_path(comment.account.username) %>
  <strong><%= link_to comment.account.username, profile_path(comment.account.username), class:"text-dark" %></strong>
  <%= comment.comment %>
  <p class="text-muted m-l-30"><%= time_ago_in_words comment.created_at %>　ago</p>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post,html: { multipart: true }  do |f| %>

<div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, class: "form-control" %>
  <%= f.hidden_field :image_cache %>
</div>

<div class="form-group">
  <%= f.label :description%>
  <%= f.text_area :description, class: "form-control" %>
</div>
<%= f.submit "Save Post", class:"btn btn-success"%>

<% end %>

app/views/posts/like.js.erb
<% if @success == true %>
$(".like-<%= @post_id %>").addClass("active");
<% else %>
$(".like-<%= @post_id %>").removeClass("active");
<% end %>

$("#post-<%= @post_id %>-likes").text("<%= @post_likes%> likes");

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render "form"%>

app/views/posts/show.html.erb
<div class="container post-details">
  <div class="row">
    <div class="col-8">
      <div class="insta-post">
        <%= image_tag @post.image.url, class:"img img-fluid" if @post.image.present?%> 
      </div>
    </div>
    <div class="col-4">
      <div class="post-meta">
        <%= link_to image_tag(@post.account.image.thumb.url, class:"img-circle"), profile_path(@post.account.username) %>
        <%= link_to @post.account.username, profile_path(@post.account.username), class:"text-dark"%>
      </div>        
      <div class="post-details">
      <div class="comments-feed">
        <%= simple_format @post.description %>   
        <%= render "posts/comments", post: @post, comments: @comments %>
        </div>
       <div class="post-actions">
          <i class="fa fa-heart like-<%= @post.id %><%= "active" if post_liked_user?(@post.id)%> fa-2x post-like" data-id="<%= @post.id%>"></i>
          <i class="fa fa-comment fa-2x post-commnet" id="post-comment"></i>
       </div>
      <p><strong id="post-<%= @post.id%>-likes"><%= @post.total_likes_count %>Likes</strong></p>
     
     
      <p class="text-muted"><%= time_ago_in_words @post.created_at %> ago</p>
    </div>
    <div class="comment-box">
      <%= form_for @comment do |f| %>
      <%= f.hidden_field :post_id, value: @post.id%>
      <%= f.hidden_field :return_to, value: "post" %>
      <div class="input-group">
      <%= f.text_field :comment, placeholder:"Add comment here...", class:"form-control post-comment" %>
      <div class="input-group-append">
      <%= f.submit "Post", class:"btn btn-success float-right"%>
      </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>